### ISSUE TITLE
Utilización de la API de JavaMail (Envío de mensaje)

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#10]
Llevar acabo y con éxito la prueba correspondiente para hacer un envió de un mensaje, una vez hecho la vinculación adecuada con el inicio de sesión de gmail,  el cual debe realizarse a través de la utilización de la API de Java (JavaMail) que nos ofrece acerca de Gmail. 

tiempo estimado de ejecución: 2 horas y 30 minutos

**Comment by JuanPerezRincon** [comment]
## # **# Aquí se encuentra un archivo  .txt  que contiene el código en java que me permite enviar un mensaje a un correo electronico en especifico**

[Envio de Mensaje.txt](https://github.com/AdvanceSoftwareSolution/proyecto/files/210578/Envio.de.Mensaje.txt)
