### ISSUE TITLE
Filtrado de datos por Asunto de Correo

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#13]
De los correos almacenados en el inbox filtrarlos por asunto del mensaje. puesto que javamail utiliza un filtrado por carpetas el cual hoy en dia gmail no utiliza. (gmail utiliza circulos de google+) .

**Comment by luismguerrero** [comment]
el filtrado de mensajes mediante el asunto fue exitoso.
Damos paso a hacer filtrado de usuario a usuario una vez obtenidos los datos filtrados por asunto, para poder realizar el conteo respectivo de cada integrante, veremos dichos resultados en una nueva tarea. 

Estos codigos ya realizados se localizan en la supcarpeta "Lectura filtrado asunto" de la carpeta JAVAMAIL dentro del repositorio.

Visualización
![hola](https://cloud.githubusercontent.com/assets/17280264/15426903/197cd0d2-1e57-11e6-9ab4-441eda4b0879.png)
