### ISSUE TITLE
Ordenamiento de Datos

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#14]
Filtrado por usuario remitente, ordenamiento en orden del correo mas viejo al mas nuevo. 

tiempo estimado 2 horas y 30 minutos

**Comment by luismguerrero** [comment]
La tarea fue realizada con éxito, se da paso al filtrado por fecha especifica. 
los codigos estan almacenados en la carpeta codigos javamail .. en la subcarpeta lectura con filtrado de usuario remitente 
![recbi](https://cloud.githubusercontent.com/assets/17280264/15160795/0d406088-16c1-11e6-999f-8d34c810c298.jpg)
