### ISSUE TITLE
Realizar e implementar las pruebas unitarias en un ejemplo usando JUnit.

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#15]
## Realice un programa en el cual se implemente las pruebas unitarias usando JUnit.
# **tiempo estimado 1 horas y 30 minutos**

**Comment by JuanPerezRincon** [comment]
### **en los dos archivos  ".txt" , se encuentra los códigos en java para el ejemplo Suma implementando**

### las pruebas unitarias con JUnit.

[SumaJUnit.txt](https://github.com/AdvanceSoftwareSolution/proyecto/files/236732/SumaJUnit.txt)

[SumaTestJUnit.txt](https://github.com/AdvanceSoftwareSolution/proyecto/files/236733/SumaTestJUnit.txt)
