### ISSUE TITLE
Ajuste en código base, estandarizado de codificacion y documentación. 

### ISSUE THREAD

**Issue by luismguerrero** [AdvanceSoftwareSolution/proyecto#18]
Según el documento definido con los estándares de codificación hacer los ajustes respectivos al código base del proyecto, así mismo realizar la documentación con la herramienta Javadoc

**Comment by JuanPerezRincon** [comment]
los ajustes  respecto al código base ya  se ha realizado y subido al repositorio, y se encuentra en la carpeta códigos javamail.
