### ISSUE TITLE
Resumen de lo acordado en la reunión 

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#4]
Redactar lo estipulado en la primera reunión para tener un recuento, y así cumplir las tareas asignadas

**Comment by JuanPerezRincon** [comment]
Fecha: 12/02/2016
Villavicencio/Meta
RESUMEN
REUNION DE INICIO (planear el desarrollo del proyecto)

En el presente documento se redacta la planificación del proyecto  de ingeniería de software, la planificación se dividió en varios aspectos importantes  como lo son el  nombre de la empresa, logo de la empresa, nombre de la aplicación, logo de la aplicación y las metodologías de desarrollo que vamos aplicar para el proyecto.
Primero que todo  empezaremos con el nombre de la empresa, todos los integrantes del proyecto eligieron el nombre de ( Advance Software Solutions) con las siglas de  A.S.S., el porque le dimos este nombre a la empresa  fue mas que todo por que nosotros  tenemos la idea de dar  soluciones  con software avanzado  a las necesidades de las personas.

En el orden de ideas que fuimos desarrollando generamos el logo de la empresa, El logo esta formado por alfabetos  las siglas (A  y S)  que significan  (Advance y Software), en la parte inferior del logo  se encuentra el  nombre de la empresa expresado en las siglas  A.S.S.  y  en la parte inferior del nombre con las siglas se encuentra  el eslogan de la empresa  que es el nombre completo de la empresa  Advance software solutions, con este logo quisimos mostrar a la empresa con una imagen  mas moderna aplicando colores llamativos.

El tercer tema que tocamos fue el nombre de la aplicación y el logo de la aplicación, empezando con el orden de ideas, se eligió primero el nombre de la aplicación. La aplicación se llamara TEAM  en español significa ( EQUIPO), el nombre  TEAM  fue elegido debido a que el objetivo del proyecto es desarrollar una aplicación que determine las interacciones en un equipo de trabajo o grupo de trabajo, basándonos en este concepto  fue que se le dio este nombre.

El logo de la empresa es algo muy importante para el equipo, es por eso que no podemos afirmar  cual será el logo de la aplicación debido a que buscamos un logo llamativo que en realidad muestre el objetivo de la aplicación y para que sirve, por eso  decidimos seguir investigando sobre como seria el logo  definitivo de la aplicación.

Con respecto a las metodologías de desarrollo, estuvimos gran tiempo en debate, debido a que queremos encontrar una metodología en la cual se implemente dentro del Gmail, sin que el usuario no tenga que  ingresar datos, ni correos para poder acceder a la aplicación, lo que queremos es que la aplicación corra dentro de Gmail como si fuera un botón mas, o una función mas de Gmail.

Dentro de las metodologías que debatimos esta la de implementar  google developers o  google play, ya que  es una plataforma que nos permite  desarrollar, publicar y distribuir con facilidad las aplicaciones directamente a los usuarios de google.
Aunque vimos mas factible la metodología de desarrollar en google, no descartamos desarrollar un aplicación independiente con un lenguaje independiente a  google y buscar un enlace que comunique nuestra  aplicación y google, para que corra el aplicativo sin ningún problema y que no tenga que pedir usuario y contraseña  cada vez que se ejecute.
