### ISSUE TITLE
Realizar el primer frame de la aplicación

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#6]
La primera fase de la aplicación en donde se vera de una forma mas estilizada el mockup inicial

**Comment by luismguerrero** [comment]
Primera visualización Web
![visual](https://cloud.githubusercontent.com/assets/17280264/13430194/08aef9a0-df92-11e5-93c0-78c8b9cda5d1.jpg)

**Comment by luismguerrero** [comment]
Los estilos heredados son de boostrap. el archivo index, favicon y el css, de estructura ya fueron subidos a Github.
