### ISSUE TITLE
Utilización de la API de JavaMail  (Inicio de sesión) 

### ISSUE THREAD

**Issue by juan5d** [AdvanceSoftwareSolution/proyecto#9]
Llevar acabo y con éxito la vinculación del sistema con el inicio de sesión de gmail, el cual debe realizarse a través de la utilización de la API de JavaMail  que nos ofrece acerca de Gmail. 

tiempo estimado de ejecución: 2 horas y 30 minutos

**Comment by JuanPerezRincon** [comment]
# *_En este documento .txt  se encuentra el código en java de  inicio de  sesión  usando la librería de JavaMail. *_

[InicioSession.txt](https://github.com/AdvanceSoftwareSolution/proyecto/files/210571/InicioSession.txt)
